# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ self, inputs, ...}: {
	flake.nixosModules.nixosHardware = { config, lib, pkgs, modulesPath, ... }: {
	  imports =
	    [ (modulesPath + "/installer/scan/not-detected.nix")
	    ];

	  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "sd_mod" "sdhci_pci" ];
	  boot.initrd.kernelModules = [ ];
	  boot.kernelModules = [ "kvm-intel" ];
	  boot.extraModulePackages = [ ];

	  fileSystems."/" =
	    { device = "/dev/mapper/luks-770c6ef9-6fb5-46eb-8fef-29291960d44b";
	      fsType = "btrfs";
	    };

	  boot.initrd.luks.devices."luks-770c6ef9-6fb5-46eb-8fef-29291960d44b".device = "/dev/disk/by-uuid/770c6ef9-6fb5-46eb-8fef-29291960d44b";

	  fileSystems."/home" =
	    { device = "/dev/mapper/luks-770c6ef9-6fb5-46eb-8fef-29291960d44b";
	      fsType = "btrfs";
	      options = [ "subvol=home" ];
	    };

	  fileSystems."/nix" =
	    { device = "/dev/mapper/luks-770c6ef9-6fb5-46eb-8fef-29291960d44b";
	      fsType = "btrfs";
	      options = [ "subvol=nix" ];
	    };

	  fileSystems."/boot" =
	    { device = "/dev/disk/by-uuid/067E-ED6F";
	      fsType = "vfat";
	      options = [ "fmask=0077" "dmask=0077" ];
	    };

	  swapDevices =
	    [ { device = "/dev/mapper/luks-61d64e22-eb57-4e23-b189-a0ef07db21e0"; }
	    ];

	  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
	  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
    };
}
